services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn --workers 3 --bind 0.0.0.0:8000 mentorship.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mentorship
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A mentorship worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A mentorship beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
